
(IN-PACKAGE :BLD-E2) 
(PROGN
 (DEFCLASS E2 (G)
           ((COEF :INITFORM (MAKE-ARRAY 4 :INITIAL-ELEMENT 0))
            (METRIC :ALLOCATION :CLASS :INITFORM (MAKE-METRIC NIL))
            (DIMENSION :ALLOCATION :CLASS :INITFORM 2)
            (SIZE :ALLOCATION :CLASS :INITFORM 4)
            (REVTABLE :ALLOCATION :CLASS :INITFORM #(1 1 1 -1))
            (BITMAP :ALLOCATION :CLASS :INITFORM #(0 1 2 3))
            (UNITVECTORS :ALLOCATION :CLASS :INITFORM (E1 E2))
            (BASISBLADES :ALLOCATION :CLASS :INITFORM (S E1 E2 E1E2))
            (BASISBLADEKEYS :ALLOCATION :CLASS :INITFORM (:S :E1 :E2 :E1E2))
            (SPEC :ALLOCATION :CLASS :INITFORM
             '((E2 S E1 E2 E1E2) (SE2 S) (VE2 E1 E2) (BVE2 E1E2) (RE2 S E1E2))
             :READER SPEC)))
 (DEFMETHOD INITIALIZE-INSTANCE :AFTER ((G E2) &KEY S E1 E2 E1E2)
   (WHEN S (SETF (GREF G :S) S))
   (WHEN E1 (SETF (GREF G :E1) E1))
   (WHEN E2 (SETF (GREF G :E2) E2))
   (WHEN E1E2 (SETF (GREF G :E1E2) E1E2)))) 
(DEFCLASS SE2 (E2)
          ((COEF :INITFORM (MAKE-ARRAY 1 :INITIAL-ELEMENT 0))
           (SIZE :ALLOCATION :CLASS :INITFORM 1)
           (BITMAP :ALLOCATION :CLASS :INITFORM #(0))
           (BASISBLADES :ALLOCATION :CLASS :INITFORM '(S)))) 
(DEFCLASS VE2 (E2)
          ((COEF :INITFORM (MAKE-ARRAY 2 :INITIAL-ELEMENT 0))
           (SIZE :ALLOCATION :CLASS :INITFORM 2)
           (BITMAP :ALLOCATION :CLASS :INITFORM #(1 2))
           (BASISBLADES :ALLOCATION :CLASS :INITFORM '(E1 E2)))) 
(DEFCLASS BVE2 (E2)
          ((COEF :INITFORM (MAKE-ARRAY 1 :INITIAL-ELEMENT 0))
           (SIZE :ALLOCATION :CLASS :INITFORM 1)
           (BITMAP :ALLOCATION :CLASS :INITFORM #(3))
           (BASISBLADES :ALLOCATION :CLASS :INITFORM '(E1E2)))) 
(DEFCLASS RE2 (E2)
          ((COEF :INITFORM (MAKE-ARRAY 2 :INITIAL-ELEMENT 0))
           (SIZE :ALLOCATION :CLASS :INITFORM 2)
           (BITMAP :ALLOCATION :CLASS :INITFORM #(0 3))
           (BASISBLADES :ALLOCATION :CLASS :INITFORM '(S E1E2)))) 
(DEFUN E2 (&KEY (S 0) (E1 0) (E2 0) (E1E2 0))
  (MAKE-INSTANCE 'E2 :COEF (VECTOR S E1 E2 E1E2))) 
(DEFUN SE2 (&KEY (S 0)) (MAKE-INSTANCE 'SE2 :COEF (VECTOR S))) 
(DEFUN VE2 (&KEY (E1 0) (E2 0)) (MAKE-INSTANCE 'VE2 :COEF (VECTOR E1 E2))) 
(DEFUN BVE2 (&KEY (E1E2 0)) (MAKE-INSTANCE 'BVE2 :COEF (VECTOR E1E2))) 
(DEFUN RE2 (&KEY (S 0) (E1E2 0)) (MAKE-INSTANCE 'RE2 :COEF (VECTOR S E1E2))) 
(DEFMETHOD GREF ((G E2) (BB SYMBOL))
  (CASE BB
    (:S (AREF (COEF G) 0))
    (:E1 (AREF (COEF G) 1))
    (:E2 (AREF (COEF G) 2))
    (:E1E2 (AREF (COEF G) 3))
    (T 0))) 
(DEFMETHOD GREF ((G SE2) (BB SYMBOL)) (CASE BB (:S (AREF (COEF G) 0)) (T 0))) 
(DEFMETHOD GREF ((G VE2) (BB SYMBOL))
  (CASE BB (:E1 (AREF (COEF G) 0)) (:E2 (AREF (COEF G) 1)) (T 0))) 
(DEFMETHOD GREF ((G BVE2) (BB SYMBOL))
  (CASE BB (:E1E2 (AREF (COEF G) 0)) (T 0))) 
(DEFMETHOD GREF ((G RE2) (BB SYMBOL))
  (CASE BB (:S (AREF (COEF G) 0)) (:E1E2 (AREF (COEF G) 1)) (T 0))) 
(DEFMETHOD GSET ((G E2) (BB SYMBOL) VAL)
  (CASE BB
    (:S (SETF (AREF (COEF G) 0) VAL))
    (:E1 (SETF (AREF (COEF G) 1) VAL))
    (:E2 (SETF (AREF (COEF G) 2) VAL))
    (:E1E2 (SETF (AREF (COEF G) 3) VAL))
    (T
     (ERROR
      (FORMAT NIL "Basis bitmap ~b doesn't exist in GA object of type E2."
              BB))))) 
(DEFMETHOD GSET ((G SE2) (BB SYMBOL) VAL)
  (CASE BB
    (:S (SETF (AREF (COEF G) 0) VAL))
    (T
     (ERROR
      (FORMAT NIL "Basis bitmap ~b doesn't exist in GA object of type SE2."
              BB))))) 
(DEFMETHOD GSET ((G VE2) (BB SYMBOL) VAL)
  (CASE BB
    (:E1 (SETF (AREF (COEF G) 0) VAL))
    (:E2 (SETF (AREF (COEF G) 1) VAL))
    (T
     (ERROR
      (FORMAT NIL "Basis bitmap ~b doesn't exist in GA object of type VE2."
              BB))))) 
(DEFMETHOD GSET ((G BVE2) (BB SYMBOL) VAL)
  (CASE BB
    (:E1E2 (SETF (AREF (COEF G) 0) VAL))
    (T
     (ERROR
      (FORMAT NIL "Basis bitmap ~b doesn't exist in GA object of type BVE2."
              BB))))) 
(DEFMETHOD GSET ((G RE2) (BB SYMBOL) VAL)
  (CASE BB
    (:S (SETF (AREF (COEF G) 0) VAL))
    (:E1E2 (SETF (AREF (COEF G) 1) VAL))
    (T
     (ERROR
      (FORMAT NIL "Basis bitmap ~b doesn't exist in GA object of type RE2."
              BB))))) 